---
title: "R Notebook"
output: html_notebook
---

## Cibersort
```{r, echo=F, warning=F, message=F}
library(tidyverse)
library(Seurat)
library(patchwork)
```

Load data - both the test pseudobulk data, and the CIBERSORTx results
```{r, warning=F, message=F, fig.width=20, fig.height=10}
seurat_pb <- readRDS("data/cibersort/seurat_test.rds")
p1 <- DimPlot(seurat_pb, group.by="cell.type")
p2 <- DimPlot(seurat_pb, group.by="cell.type.4")
p1 + p2
```
What does the signature matrix look like?
```{r, message=F, warning=F}
sig.genes <- read_tsv("data/cibersort/sig.genes.tsv")
p1 <- DoHeatmap(seurat_pb[,sample(colnames(seurat_pb), 1000)], features=sig.genes$gene, group.by="cell.type", label=F) + theme(axis.text.y=element_blank(), axis.ticks.y=element_blank())
p2 <- DoHeatmap(seurat_pb[,sample(colnames(seurat_pb), 1000)], features=sig.genes$gene, group.by="cell.type.4", label=F) + theme(axis.text.y=element_blank(), axis.ticks.y=element_blank())
p1 + p2
```
Now just look at the signature matrices
```{r, warning=F, message=F, fig.width=20, fig.height=10}
sig.all <- read_tsv("data/cibersort/inputs/signature_matrix.tsv") %>%
            gather(!gene, key="type", value="count")
sig.4 <- read_tsv("data/cibersort/inputs/signature_matrix_4type.tsv") %>% 
          gather(!gene, key="type", value="count")
p1 <- ggplot(sig.all, aes(x=factor(type, levels=levels(seurat_pb$cell.type)), y=gene, fill=count)) + geom_tile() + theme(axis.text.y=element_blank(), axis.ticks.y=element_blank())
p2 <- ggplot(sig.4, aes(x=factor(type, levels=levels(seurat_pb$cell.type.4)), y=gene, fill=count)) + geom_tile() + theme(axis.text.y=element_blank(), axis.ticks.y=element_blank())
p1 + p2
```

Save true pseudobulk labels for downstream analysis
```{r, echo=F, warning=F, message=F}
day.ind <- as_tibble(seurat_pb$day.ind, rownames="cell")
cell.types <- as_tibble(seurat_pb$cell.type, rownames="cell")
cell.types.4 <- as_tibble(seurat_pb$cell.type.4, rownames="cell")
write_tsv(day.ind, "data/cibersort/pseudobulk_samples.tsv")
write_tsv(cell.types, "data/cibersort/pseudobulk_labels.all.tsv")
write_tsv(cell.types.4, "data/cibersort/pseudobulk_labels.4.tsv")
```
